site_name: FreiCar Docs
nav:
    - Software:
        - Home: 'index.md'
        - Environment: 'environment.md'
        - First Steps: 'first_steps.md'
        - Simulator: 'simulator.md'
        - Software Overview: 'nodes/freicar_overview.md'
        # - FreiCar Map: 'nodes/freicar_map.md'
        # - FreiCar Agent: 'nodes/freicar_agent.md'
#        - Competition Rules: 'competition_rules.md'
        # - Code Style: 'code_style.md'
    - Real-World Cars:
        - Safety: 'safety_rules.md'
        - Vive Tracking: 'vive_tracking.md'
        - Starting, Charging,..: 'starting_charging_etc.md'
        - Chaperone: 'chaperone.md'
        - Remote Control: 'remote.md'
        - ROS Network Setup: 'network_setup.md'
        - Ubuntu Installation: 'installation.md'
    - Car Assembly:
        - Subassemblies: 'assembly/index.md'
#        - Subassembly - ESC: 'assembly/esc_case.md'
#        - Subassembly - PC: 'assembly/pc_case.md'
#        - Subassembly - Front Sensors: 'assembly/front_sensor.md'
#        - Subassembly - Rear Sensors: 'assembly/rear_sensor.md'
        - Car Integration: 'assembly/car_asm.md'
        - Electronics: 'assembly/electronics.md'

theme: readthedocs
